(function(a,b){a.prototype.find===b&&(a.prototype.find=function(a){for(var c=0;c<this.length;++c)if(a(this[c]))return this[c];return null})})(Array);(function(a,b){a.prototype.join===b&&(a.prototype.join=function(a){for(var c="",e=0;e<this.length;++e)0<e&&(c+=a),c+=this[e];return c})})(Array);(function(a,b){a.prototype.map===b&&(a.prototype.map=function(a){for(var c=[],e=0;e<this.length;++e)c[e]=a(this[e]);return c})})(Array);
(function(a,b){a.prototype.toObject===b&&(a.prototype.toObject=function(){for(var a={},c=0;c<this.length;c+=2)this[c]!==b&&(a[this[c]]=this[c+1]);return a})})(Array);jQuery.fn.bg=function(a){return this.css("background-image","url("+a+")")};jQuery.json=function(a,b,d){b.dataType="json";return this.ajax(a,b).done(function(a,e,b){return d.call(this,b.responseJSON)}).fail(function(a,e,b){return d.call(this,a.responseJSON)})};
Utils=function(a,b){function d(c){return 0<a.trim(c).length}return{getCsrfToken:function(){return a('meta[name="csrf-token"]').attr("content")},debounce:function(a,e){var g;return function(){g&&b.clearTimeout(g);var f=this,d=arguments;g=b.setTimeout(function(){a.apply(f,d);g=null},e)}},serialize:function(){var c={INPUT:function(a){return[a.attr("name"),a.val()].toObject()}};return function(e){var b=c[e.prop("tagName")],b=b&&b(e)||{};return a.extend(b,e.data("params"))}}(),$tag$:function(c){if("undefined"===
typeof c.tagName)throw Error("Target element must be a tag.");return a(c)},isBlank:function(a){return!d(a)},isPresent:d,cropFields:function(c,e){a.each(e,function(a,e){c[a]&&c[a].length>e&&(c[a]=c[a].substr(0,e-3)+"...")})},countSymbols:function(a){return a.replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g,"_").length},limitSymbols:function(a,e){for(var b="",f=0,d,k,l=0;l<a.length&&(d=a.charAt(l),k=d.charCodeAt(0),b+=d,55296<=k&&56319>=k&&(b+=a.charAt(++l)),++f!=e);l++);return b}}}(jQuery,window);
Actions=function(a,b,d){function c(b){return function(c){var d=e[a(this).data(b)];d&&(d.handler(this,c),!1!==d.options.preventDefault&&c.preventDefault())}}var e={};a(b).on("submit","form[data-action]",c("action")).on("click","a[data-action]",c("action")).on("click","input[data-action]",c("action")).on("input paste","input[data-input]",d.debounce(c("input"),500));return function(a,b,c){e[a]={handler:b,options:c||{}}}}(jQuery,document,Utils);
Ajax=function(a,b){function d(e,c,d){var h=b.$tag$(c);e=a.extend(!0,{url:h.data("url")||h.attr("href"),type:e,data:b.serialize(h),context:c},d);return a.ajax(e)}function c(e,c){c=a.extend(!0,{},c,{headers:{"X-CSRF-Token":b.getCsrfToken()}});return d("POST",e,c)}return{get:function(a,b){return d("GET",a,b)},post:c,_put:function(b,d){d=a.extend(!0,{},d,{data:{_method:"PUT"}});return c(b,d)},_delete:function(b,d){d=a.extend(!0,{},d,{data:{_method:"DELETE"}});return c(b,d)}}}(jQuery,Utils);
Mutex=function(a){return{acquire:function(b){b=a(b);if(b.data("mutex"))return!1;b.data("mutex",!0);return!0},release:function(b){a(b).removeData("mutex")}}}(jQuery);
Pages=function(a,b){function d(a,b,d){a=a+"/"+b;c[a]?c[a].push(d):c[a]=[d]}var c={};a(b).on("page:change",function(e){var d=a(b.body).data("id"),f=d&&d.split("/")||[],d=f[0],f=f[1],f=a.unique((c["*/*"]||[]).concat(c[d+"/*"]||[]).concat(c[d+"/"+f]||[])),h;for(h in f)f[h].call(this,e)});return function(a,b){for(var c in a){var h=a[c];if("*"===c)"*"===h&&d(c,h,b);else if("*"===h)d(c,h,b);else for(var k in h)d(c,h[k],b)}}}(jQuery,document);
Turbolinkz=function(a,b,d,c,e){function g(){return c==e||!c.supported||!f.test(b.navigator.userAgent)}var f=/android|iphone|ipad|ipod/i;a(b.document).ready(function(b){c==e?a(d).trigger("page:change",b):g()&&a(d.body).attr("data-no-turbolink",!0)});return{visit:function(a){g()?b.location.href=a:c.visit(a)},isDisabled:g,isEnabled:function(){return!g()}}}(jQuery,window,document,window.Turbolinks);
Ads=function(a,b,d,c,e){function g(){a("#topMenu").stop().animate({top:"0px"},{duration:300})}function f(){var b=a(q).data("config")||{};return a.extend({},n,b)}function h(c){a(q).data("status",c);"SUCCESS"===c?0<a(b).scrollTop()&&k():m()}function k(){var c=a(q),e=c.data("status");if("SUCCESS"===e)a("#topMenu").stop().animate({top:t},{duration:300}),c.show();else if("LOADING"!==e){c.data("status","LOADING");try{b.SomaJS.loadAd(f(),h)}catch(d){}}}function l(){b.clearTimeout(u);var c=Math.max(0,a(b).scrollTop());
t||(t="-"+a("#topMenu").height()+"px");0===c?(a(q).hide(),g()):c<r?(a(q).hide(),g(),u=b.setTimeout(k,5E3)):c>r&&k();r=c}function p(){if(b.SomaJS!==e&&0<a(q).length)a(b).on("scroll",v)}function m(){b.clearTimeout(u);a(b).off("scroll",l)}var n={publisherId:0,adSpaceId:0,adDivId:"smaato"},t=null,q="#"+n.adDivId,r=0,u=null,v=c.debounce(l,100);if(d.isDisabled())a(b).on("load",p);else a(b).on("page:change",p).on("page:before-change",m)}(jQuery,window,Turbolinkz,Utils);
PageLoader=function(a,b){function d(){a("#loaderMother").show()}function c(){a("#loaderMother").hide()}a(b).on("page:before-change",d).on("page:change",c);return{show:d,hide:c}}(jQuery,document);AjaxUI=function(a,b){return{get:function(d,c){b.show();return a.get(d,c).always(PageLoader.hide)}}}(Ajax,PageLoader);
Browser=function(a,b,d){function c(){a(b.document.body).addClass("forceiepaint").removeClass("forceiepaint")}var e=/IEmobile\/11/i.test(b.navigator.userAgent);if(d.isEnabled()&&e)a(b).on("page:change",c);return{ie11:e}}(jQuery,window,Turbolinkz);
Form=function(a,b,d){function c(c,g){var f=b.$tag$(c),h=a("<form>").attr({action:f.data("url")||f.attr("href"),target:d.ie11?null:f.data("window"),method:"POST"}),f=a.extend({},g,b.serialize(f),{authenticity_token:b.getCsrfToken()}),k;for(k in f)a("<input>").attr({name:k,value:f[k]}).appendTo(h);h.hide().appendTo("body").submit()}return{post:function(a){c(a)},put:function(a){c(a,{_method:"PUT"})},"delete":function(a){c(a,{_method:"DELETE"})}}}(jQuery,Utils,Browser);
Button=function(a,b,d){function c(c){c=a(c);a(c.data("target")).submit()}return{submit:c,submitOnce:function(a){b.acquire(a)&&c.call(this,a)},postOnce:function(c){if(b.acquire(c)){var g=a(c).data("method")||"post";if(d[g])d[g](c)}}}}(jQuery,Mutex,Form);
Captcha=function(a,b,d,c,e){function g(c){b.clearTimeout(h);a(".captcha.askfm",c).length&&(h=b.setTimeout(function(){f(c)},3E5))}function f(b,d,e){var f=a(".captchaContainer",b);1===f.length&&(d&&f.data("params",d),c.get(f[0]).done(function(a){f.html(a||"").toggle(!!a);g(b);e&&e()}))}var h=null;a(document).on("page:change",function(){a("form").has(".captchaContainer").each(function(){g(this)})});return{reloadAction:function(c){if(d.acquire(c)){var b=a(c),f=a(c).closest("form"),b=e.serialize(b);a.isEmptyObject(b)&&
(b=null);Captcha.reload(f,b,function(){d.release(c)})}},reload:f,onRecaptcha2Load:function(){a(".g-recaptcha").each(function(){b.grecaptcha.render(this,{sitekey:a(this).data("sitekey"),"expired-callback":b.grecaptcha.reset})})}}}(jQuery,window,Mutex,Ajax,Utils);Recaptcha2onLoad=Captcha.onRecaptcha2Load;
Checkbox=function(a,b){function d(a,c){return function(d,h){h=a!==b?a:!(c?!0===h:"true"===h);return c?h:h?"true":"false"}}function c(c,b){var f=a(c),h=f.data("target"),h=h?a("#"+h):f,k=h.next("input");h.toggleClass(f.data("class"),b);k.is(":checkbox")?k.prop("checked",d(b,!0)):k.val(d(b,!1))}return{toggle:c,onToggle:function(a,b){c(a)}}}(jQuery);
Config=function(a){function b(a){if(null===d)throw Error("JS configuration not loaded yet");if("undefined"===typeof d[a])throw Error("JS configuration not found for key "+a);return d[a]}var d=null,c=[];return{register:function(a){null===d?c.push(a):a.apply(this)},init:function(a){d=a;for(a=0;a<c.length;++a)c[a].apply(this);c=[]},get:b,isDebug:function(){return"production"!=b("env")&&"#debug-off"!=a.location.hash}}}(window);
Flash=function(a,b,d){function c(){return a(this).delay(d.get("flash:delay")).fadeOut("slow").dequeue()}function e(a,b){k.html(a);h.finish().removeClass("alert notice").addClass(b).show(0).queue(c)}function g(a){e(a,"alert")}function f(a){e(a,"notice")}var h=null,k=null;a(b).on("page:change",function(){h=a("#mainFlash");h.is(":visible")&&h.queue(c);k=h.find(".content")});return{error:g,notice:f,message:function(a,c){a?g(a):c&&f(c)},hideAction:function(a){h.stop(!0,!0).fadeOut("slow")}}}(jQuery,document,
Config);
FormXHR=function(a,b,d,c,e,g,f,h){function k(a,c){var b;a:{for(b in p)if(a.hasClass(b))break a;b=void 0}var d=p[b],e=a.parent();(e.hasClass(b+"Padding")?e:a).toggleClass(d,c)}function l(b){if(b.error){g.error(b.error);b=b.fields;for(var l in b)k(a(this[b[l]]),!0);a(this.authenticity_token).val(f.getCsrfToken());h.reload(this);e.hide();c.release(this)}else b.notice?(g.notice(b.notice),e.hide(),c.release(this)):b.url&&d.visit(b.url)}var p={simpleForm:"simpleFormPadding-error",inputForm:"simpleFormPadding-error",selectForm:"simpleFormPadding-error"},
m=a.map(p,function(a,b){return"."+b}).join(",");a(b).on("focus blur",m,function(){k(a(this),!1)});return{submit:function(b){c.acquire(b)&&(e.show(),a.json(b.action,{data:a(b).serializeArray(),type:b.method,context:b},l))}}}(jQuery,document,Turbolinkz,Mutex,PageLoader,Flash,Utils,Captcha);FormXHR2=function(a){return{upload:function(b,d){var c=new FormData(b),e;for(e in d)c.append(e,d[e]);return a.ajax({url:a(b).data("upload-url"),type:"POST",data:c,async:!0,cache:!1,contentType:!1,processData:!1,context:b})}}}(jQuery);
Gemini=function(a,b,d,c,e,g){function f(){var b={};s.each(function(){var c=a(this).data("section");b[c]=(b[c]||0)+1});return b}function h(b){var c=[];a.each(b,function(a,b){c.push({section:a,imgType:"rectangle",adsRequested:b,process:q,complete:t,error:n,testing:g.isDebug()})});return c}function k(){v&&w&&(w=!1,s.data("loading",!0),Yahoo.q=h(f()),Yahoo.init())}function l(){v=!0;k()}function p(b,c){return s.filter(function(){return a(this).data("section")===b}).filter(function(){return a(this).data("loading")}).filter(c||
"*").removeData("loading")}function m(b){p(b).each(function(){a(this).find(".gemini-container.default").replaceAll(this).show()})}function n(a,b){m(b)}function t(a){m(a&&a.section)}function q(b,c){e.cropFields(c,u);var d=p(b,":first"),f=d.find("script"),f=a.trim(f.html()),f=Yahoo.createElement(Yahoo.format(f,c));d.replaceWith(f);return f}function r(){s=a(".gemini-block");0<s.length&&(v||a.ajax({url:"https://s.yimg.com/av/gemini/ga/gemini-api.js",dataType:"script",cache:!0}).done(l),w=!0,k())}var u=
{title:50,description:100,sponsor:25},v=!1,w=!1,s=null;g.register(function(){if(c.isEnabled())a(d).on("page:change",r);else a(d).ready(r)})}(jQuery,window,document,Turbolinkz,Utils,Config);
GoogleAnalytics=function(a,b,d,c){function e(a){c.isDebug()||(a?b._gaq.push(["_trackPageview",a]):b._gaq.push(["_trackPageview"]),b._gaq.push(["_trackPageLoadTime"]))}function g(){var a,c;b._gaq=[];b._gaq.push(["_setDomainName","none"]);b._gaq.push(["_setAccount","UA-12308109-2"]);c=f.createElement("script");c.type="text/javascript";c.async=!0;c.src=("https:"===f.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";a=f.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,
a);d.isEnabled()?f.addEventListener("page:change",function(){e()},!0):e()}var f=b.document;a(document).ready(function(){c.register(g)})}(jQuery,window,Turbolinkz,Config);LabeledField=function(a,b){function d(){a(this).toggleClass("mask-form-active",0!==a(this).val().length)}a(b.document).on("focus blur paste input","input.mask-form, textarea.mask-form",d).on("page:change",function(){b.setTimeout(function(){a("input.mask-form, textarea.mask-form").each(d)},0)})}(jQuery,window);
Motivator=function(a,b){var d;a(b).on("page:change",function(){d=a(".emptyViewContent,.emptyResults")});return{toggle:function(a){d.toggle(a)}}}(jQuery,document);
ScrollViewMore=function(a,b,d){function c(){g=e.scrollTop()+e.height();f()}var e=a(b),g=0,f=d.debounce(function(){var b=a("#contentArea .viewMore");if(1===b.length){var c=.65*e.height();b.offset().top-g<c&&b.click()}},100);return{selector:"#contentArea .viewMore",bind:function(){a(b).off("scroll",c);0<a("#contentArea .viewMore").length&&(a(b).on("scroll",c),c())}}}(jQuery,window,Utils);
Pager=function(a,b,d,c){function e(){h=0<a(k).length;b.toggle(0===g&&!h);if(f){var c=a("#itemCount"),e=g-f+parseInt(c.text());c.text(e)}f=g;d.bind()}var g=null,f=null,h=!1,k=d.selector;a(c).on("page:change",function(){g=a(".item",".item-chunk").length;f=null;e()});return{$prependWithItems:function(b,c){var d=a(c).prependTo(b),f=d.find(".item").length;g+=f;e();return d},$replaceWithItems:function(b,c){var d=a(c).replaceAll(b).find(".item").length;g+=d;e();return d},$removeClosestItem:function(b){a(b).closest(".item").remove();
g-=1;e()},$substituteItems:function(b,c){g=a(b).html(c).find(".item").length;e();return g}}}(jQuery,Motivator,ScrollViewMore,document);
MassAsk=function(a,b,d,c,e,g){function f(b){var c;c=a.extend({maxCount:e.get("mass_ask:selection_limit"),minCount:0,delta:0},b);b=a("#SelectedQuestionUsers a").length+c.delta;var d=b>=c.minCount&&b<=c.maxCount;c=c.maxCount;var f=a("#topBarCounter");d&&f.text(b+"/"+c);f.toggleClass("highlightText-red",!d);return d}function h(){a("#SelectedQuestionUsers a").each(function(){var b=a(this).data("login");a('#MassAskSearch a[data-login="'+b+'"] .listItemCheckbox').addClass("listItemCheckbox-checked")})}
function k(c){g.$substituteItems("#MassAskSearch",c||null);a("#MassAskSearch").toggle(c?!0:!1);h();b.release(this)}c({questions:["create"]},function(){f()});return{onSubmit:function(b,c){var d=a(b);a("#SelectedQuestionUsers a").each(function(){var b=a(this).data("login");a('<input type=hidden name="question[logins][]">').val(b).appendTo(d)});f({minCount:1})||c.preventDefault()},onToggle:function(b){var c=a(".listItemCheckbox",b);if(c.hasClass("listItemCheckbox-checked")){var d=f({delta:-1});d&&(b=
a(b).data("login"),a('#SelectedQuestionUsers a[data-login="'+b+'"]').remove())}else(d=f({delta:1}))&&a(b).clone().appendTo("#SelectedQuestionUsers");(b=d)&&c.toggleClass("listItemCheckbox-checked")},onSearch:function(a){b.acquire(a)&&d.get(a).done(k)}}}(jQuery,Mutex,AjaxUI,Pages,Config,Pager);
Notifications=function(a,b,d){function c(){b.clearTimeout(h);f&&(h=b.setTimeout(e,f))}function e(){var b=a("#notifications").data("poll-url");b&&a.getJSON(b).done(g).always(c)}function g(b){a.each(b||{},function(b,c){var d=c||0,e=999<d?"99+":d.toString();a({questions:"#newQuestionCounter",perks:"#newPerkCounter",replies:"#newReplyCounter"}[b]).text(e).toggle(0<d)})}var f=null,h=null;a(b.document).on("page:change",function(){f=d.get("poller:interval");a("#notifications").length&&c()})}(jQuery,window,
Config);
PhotoAnswer=function(a,b,d,c){function e(){a(".loaderUpload",this).hide();this.reset();b.release(this)}function g(b){var d=this.rid.value;a("#answerType").val("photo");a("#photoUrl").val(d);a("#photoThumb").bg(b.thumbUrl);a("#uploadForm").hide();a(".uploadButtons").toggle();c.notice(a(this).data("success-text"))}function f(){c.error(a(this).data("failure-text"))}return{submitAction:function(c){c.file.value&&b.acquire(c)&&(a(".loaderUpload",c).show(),d.upload(c,{ts:(new Date).getTime()}).done(g).fail(f).always(e))},removeAction:function(b){a("#answerType").val(null);
a("#photoUrl").val(null);a(".uploadButtons").toggle()}}}(jQuery,Mutex,FormXHR2,Flash);
Poller=function(a,b,d,c){function e(a){a&&(n+=c.$replaceWithItems("#newItemsReady",a));n<k&&f()}function g(){a.get(p,{counter:n},e)}function f(){(p=a("#newItemsReady").data("poll-url"))&&l&&(m=b.setTimeout(g,l))}function h(){var b=0;a("#newItemsReady").nextUntil(":visible","div.item-chunk.poll-items").find(".likeButtonCounter").each(function(){b+=parseInt(a(this).text())});return b}var k=null,l=null,p=null,m=null,n=0;a(b.document).on("page:change",function(){k=d.get("poller:cache_limit");l=d.get("poller:interval");
b.clearTimeout(m);m=null;f();n=0});return{clickAction:function(){ProfileTabCounters.update({answers:n,likes:h});b.clearTimeout(m);m=null;f();n=0;a("#newItemsReady").hide().nextUntil(":visible","div.item-chunk.poll-items").prependTo("#item-pager").show().removeClass("highlight")}}}(jQuery,window,Config,Pager);
PopupCallback=function(a,b){function d(c,d){var g=a(c),f=g.get(0);g.data("connected",d);b.toggle(f,d)}return{permit:{facebook:function(a){d("#facebook_switch",a)},twitter:function(a){d("#twitter_switch",a)},vkontakte:function(a){d("#vkontakte_switch",a)}}}}(jQuery,Checkbox);
ProfileTabCounters=function(a,b){var d=!1,c={answers:"#profileTabAnswerCount",likes:"#profileTabLikeCount"};b({profile:["answers","likes","gifts","answer"]},function(){d=!0});return{update:function(b){d&&a.each(b,function(b,d){a.isFunction(d)&&(d=d());a(c[b]).text(function(a,b){return parseInt(b)+parseInt(d)})})}}}(jQuery,Pages);
(function(a,b,d){function c(){var b=a(this),c=a("#"+b.data("counter")),f=b.data("limit");c.toggle(500>f).text(f);b.on("input paste",function(){var a=b.val(),k=f-d.countSymbols(a);0>k&&(b.val(d.limitSymbols(a,f)),k=0);c.toggle(500>k).text(k)})}a(b.document).on("page:change",function(){a("textarea[data-counter][data-limit]").each(c)})})(jQuery,window,Utils);
UserAttachment=function(a,b,d,c,e){function g(c){a(".loaderUpload",c).hide();c.reset();b.release(c)}function f(){var b=a(this);e.error(b.data("failure-text"));g(this)}function h(){var b=a(this);a("#profilePictureSettings-preview").bg(b.data("params").thumbUrl);a("#removeAttachmentMenu").show();e.notice(b.data("success-text"));g(this)}function k(b,c,e){a(this).data("params",b);d.post(this).done(h).fail(f)}return{submitAction:function(d){d.file.value&&b.acquire(d)&&(a(".loaderUpload",d).show(),c.upload(d).done(k).fail(f))}}}(jQuery,
Mutex,Ajax,FormXHR2,Flash);Viewport=function(a){return{scrollToItems:function(b){var d=a("body"),c=a("#topMenu");d.animate({scrollTop:b.position().top-c.height()})}}}(jQuery);Actions("CaptchaReload",Captcha.reloadAction);Actions("FormXHRSubmit",FormXHR.submit);Actions("ButtonSubmit",Button.submit);Actions("ButtonSubmitOnce",Button.submitOnce);Actions("ButtonPostOnce",Button.postOnce);Actions("CheckboxToggle",Checkbox.onToggle);
Actions("BlockToggle",function(a){return function(b){b=a(b).data("target");a(b).stop(!1,!1).slideToggle()}}(jQuery));Actions("FlashShow",function(a,b){return function(d){var c=a(d);d=c.data("error");c=c.data("notice");b.message(d,c)}}(jQuery,Flash));Actions("FlashHide",Flash.hideAction);
Actions("FollowToggle",function(a,b){function d(a,b){a.remove()}function c(a){var c=$(this),h;a:{if(c.data("toggle")){for(h in e)if(c.hasClass(h)){h=e[h];break a}throw new Exception("UI handler for FollowToggle action not found.");}h=d}h(c,a);b.release(this)}var e={"friendsListItem-button":function(a,b){a.data("url",b.url).toggleClass("friendsListItem-unfollow").toggleClass("friendsListItem-follow")},profileButton:function(a,b){a.data("url",b.url).text(b.text).toggleClass("profileButton-grey").toggleClass("profileButton-green")}};
return function(d){b.acquire(d)&&a.post(d).done(c)}}(Ajax,Mutex));Actions("SignupSubmit",function(a,b){return function(a){a.user_gmt_offset.value=(new Date).getTimezoneOffset();b.submit(a)}}(jQuery,FormXHR));Actions("ServicePermit",function(a,b,d){return function(c){a(c).data("connected")?d.toggle(c):b.post(c)}}(jQuery,Form,Checkbox));Actions("ItemsMore",function(a,b,d){function c(a,b,c){d.$replaceWithItems(this,a)}return function(b){a.acquire(b)&&Ajax.get(b).done(c)}}(Mutex,AjaxUI,Pager));
Actions("ItemsPoll",Poller.clickAction);Pages({answers:["video","photo"],profile:["avatar"]},function(a){return function(){a("body").css("background-color","#000");a("#mediaContainer").css("top",a("#topMenu").height())}}(jQuery));Actions("PromoClick",function(a,b,d){function c(c){c?a.location=c.url:a.location.reload();b.release(this)}return function(a){b.acquire(a)&&d.post(a).done(c)}}(window,Mutex,Ajax));
Actions("AnswerLike",function(a,b){function d(a){$(a).addClass("likeButtonHeart-liked").prev("a.likeButtonCounter").text(function(a,b){return parseInt(b)+1}).show();ProfileTabCounters.update({likes:1})}return function(c){b.acquire(c)&&(d(c),a.post(c))}}(Ajax,Mutex));Actions("QuestionDelete",function(a,b){return function(d){b.$removeClosestItem(d);a._delete(d)}}(Ajax,Pager));
Actions("AnswerDelete",function(a,b,d){return function(c){var e=$(c).data("confirm");if(!e||d.confirm(e)){var e={answers:-1},g=$(c).closest(".streamItem").find(".likeButtonOwn").text();g&&(e.likes=-parseInt(g));ProfileTabCounters.update(e);b.$removeClosestItem(c);a._delete(c)}}}(Ajax,Pager,window));
Actions("QuestionRandom",function(a,b,d,c){function e(b,e,h){b=d.$prependWithItems("#item-pager",b);c.scrollToItems(b.show().removeClass("highlight"));a.release(this)}return function(c){a.acquire(c)&&b.post(c).done(e)}}(Mutex,Ajax,Pager,Viewport));Actions("MassAskSubmit",MassAsk.onSubmit,{preventDefault:!1});Actions("MassAskToggle",MassAsk.onToggle);Actions("MassAskSearch",MassAsk.onSearch);
Actions("Search",function(a,b,d,c){function e(a){$("#searchResults").toggle("#searchResults"===a);$("#searchOptions").toggle("#searchOptions"===a);$("#searchEmpty").toggle("#searchEmpty"===a)}function g(a){c.$substituteItems("#searchResults",a||null);e(a?"#searchResults":"#searchEmpty");b.release(this)}return function(c){d.isPresent(c.value)||$(c).data("query-blank")?b.acquire(c)&&a.get(c).done(g):e("#searchOptions")}}(AjaxUI,Mutex,Utils,Pager));
Actions("SignupCheck",function(a,b,d,c,e){function g(b,c){c?a(b).parent().addClass("simpleFormPadding-error").removeClass("simpleFormPadding-valid"):a(b).parent().addClass("simpleFormPadding-valid").removeClass("simpleFormPadding-error")}function f(a){a=a&&a.error||null;g(this,a);e.message(a,null);d.release(this)}return function(a){b.isPresent(a.value)?d.acquire(a)&&c.post(a).done(f):g(a,!0)}}(jQuery,Utils,Mutex,Ajax,Flash));Actions("AttachmentSubmit",UserAttachment.submitAction);
Actions("PhotoSubmit",PhotoAnswer.submitAction);Actions("PhotoRemove",PhotoAnswer.removeAction);Actions("UserBlockDelete",function(a,b,d,c,e){function g(a){c.$removeClosestItem(this);e.message(a.error,a.notice);d.release(this)}return function(a){d.acquire(a)&&b._delete(a).done(g)}}(jQuery,Ajax,Mutex,Pager,Flash));